In [1]:
import os
print(os.getcwd())
os.chdir("/Users/isaacsantelli/personal_work/AdventOfCode")
from local import advent_path
from statistics import mode, mean
import numpy as np
# import strcspn

/Users/isaacsantelli/personal_work/AdventOfCode/Advent2021/scripts


In [58]:
with open(f"Advent2021/inputs/input4.txt") as f:
    bingo_input  = f.readlines()

def strip_rows(bingo_input):
    return [p.strip() for p in bingo_input]

bingo_input = strip_rows(bingo_input)

def parse_read_numbers(bingo_input):
    numbers_read = bingo_input[0]
    numbers = numbers_read.split(',')
    return [int(i) for i in numbers]

def create_ind_boards(board_rows):
    board_rows = [row.split() for row in board_rows]
    board_rows = [list(map(int, row)) for row in board_rows]
    board_rows = np.array(board_rows)
    hits = np.zeros_like(board_rows)
    full_board = np.stack([board_rows, hits], axis=0)
#     print(full_board)
    return full_board
    
def parse_bingo_boards(bingo_input):
    bingo_input = bingo_input[2:]
    board_rows = []
    boards = []
    for row in bingo_input:
        if row == '':
            board = create_ind_boards(board_rows)
            board_rows = []
            boards.append(board)
        else:
            board_rows.append(row)
    return boards

numbers = parse_read_numbers(bingo_input)
boards = parse_bingo_boards(bingo_input)
# boards
# numbers
# # print(boards[0])
# boards[0][0][0][0] = 34
# print(boards[0][0])
# print()
# arr1 = boards[0][0] == 34
# arr2 = boards[0][1] == 1
# arr = np.logical_or(arr1, arr2)
# boards[0][1] = np.where(arr, 1, 0)
# print(boards[0])

# arr1 = boards[0][0] == 62
# arr2 = boards[0][1] == 1
# arr = np.logical_or(arr1, arr2)
# boards[0][1] = np.where(arr, 1, 0)
# print(boards[0])

# np.sum(boards[0][1], axis=1).max()

# t = np.where(boards[0][0] == 34)
# t = [list(p) for p in t]
# print(t)
# for z in zip(t[0], t[1]):
#     print(z)
# 


In [88]:
def initialize_fresh_boards(boards):
    new_list = []
    for board in boards:
        new_list.append(np.copy(board))
    return new_list

def run_bingo_game(numbers, boards):
    fresh_copy = initialize_fresh_boards(boards)
    for number in numbers:
        print(f'We rolled .... {number} !!')
        bingo = check_all_boards(number, fresh_copy)
        if len(bingo) > 0: 
            break
    d = {"bingo": bingo[0], 'number': number}
    return  d

def check_all_boards(number, boards, excluded=[]):
#     print(len(boards))
    best = 0
    winners = []
    for i, board in enumerate(boards):
        if i in excluded:
            pass
        else:
            check_board_and_update(board, number)
            if is_bingo(board):
                print('BINGO!!')
                print(f"Board: {i}")
                winners.append((i, board))
    return winners
    
def check_board_and_update(board, number):
    hits = board[0] == number
    old_hits = board[1] == 1
    arr = np.logical_or(hits, old_hits)
    board[1] = np.where(arr, 1, 0)

def is_bingo(board):
    hit_array = board[1]
    rows = np.sum(hit_array, axis=0).max()
    columns = np.sum(hit_array, axis=1).max()
    if rows == 5 or columns == 5 :
        return True
    else:
        return False
    
d = run_bingo_game(numbers, boards)

def compute_bingo_score(board, final_number):
    print(board)
    logical_arr = board[1] == 0
    remaining_sum = np.where(logical_arr, board[0], 0).sum()
    print(remaining_sum * final_number)
    
print(d['bingo'])
compute_bingo_score(d['bingo'][1], d['number'])


We rolled .... 14 !!
We rolled .... 30 !!
We rolled .... 18 !!
We rolled .... 8 !!
We rolled .... 3 !!
We rolled .... 10 !!
We rolled .... 77 !!
We rolled .... 4 !!
We rolled .... 48 !!
We rolled .... 67 !!
We rolled .... 28 !!
We rolled .... 38 !!
We rolled .... 63 !!
We rolled .... 43 !!
We rolled .... 62 !!
We rolled .... 12 !!
We rolled .... 68 !!
We rolled .... 88 !!
We rolled .... 54 !!
We rolled .... 32 !!
We rolled .... 17 !!
BINGO!!
Board: 40
(40, array([[[34, 10, 81, 75, 42],
        [27, 67, 59, 20, 87],
        [45, 17, 46, 23, 76],
        [40,  4, 77, 25, 96],
        [18,  8, 88, 53, 32]],

       [[ 0,  1,  0,  0,  0],
        [ 0,  1,  0,  0,  0],
        [ 0,  1,  0,  0,  0],
        [ 0,  1,  1,  0,  0],
        [ 1,  1,  1,  0,  1]]]))
[[[34 10 81 75 42]
  [27 67 59 20 87]
  [45 17 46 23 76]
  [40  4 77 25 96]
  [18  8 88 53 32]]

 [[ 0  1  0  0  0]
  [ 0  1  0  0  0]
  [ 0  1  0  0  0]
  [ 0  1  1  0  0]
  [ 1  1  1  0  1]]]
14093


In [90]:
def find_last_winning_board(boards, numbers):
    boards = initialize_fresh_boards(boards)
    out_of_the_game = []
    for number in numbers:
        print(f'We rolled .... {number} !!')
        remaining = len(boards) - len(out_of_the_game)
        print(f"{remaining} boards left in the game")
        bingo = check_all_boards(number, boards, out_of_the_game)
        if len(bingo) > 0 and len(boards) == 1:
            break
        elif len(bingo) > 0: 
            print(f"Elimitating {len(bingo)} boards from the game")
            indices = [b[0] for b in bingo]
            out_of_the_game += indices
#             eliminate_victorious_boards(indices, boards)
    d = {"bingo": bingo[0], 'number': number}
    return  d
    
# def eliminate_victorious_boards(indices_to_delete, boards):
#     for i in indices_to_delete:
#         del boards[i]
        
find_last_winning_board(boards, numbers)

We rolled .... 14 !!
99 boards left in the game
We rolled .... 30 !!
99 boards left in the game
We rolled .... 18 !!
99 boards left in the game
We rolled .... 8 !!
99 boards left in the game
We rolled .... 3 !!
99 boards left in the game
We rolled .... 10 !!
99 boards left in the game
We rolled .... 77 !!
99 boards left in the game
We rolled .... 4 !!
99 boards left in the game
We rolled .... 48 !!
99 boards left in the game
We rolled .... 67 !!
99 boards left in the game
We rolled .... 28 !!
99 boards left in the game
We rolled .... 38 !!
99 boards left in the game
We rolled .... 63 !!
99 boards left in the game
We rolled .... 43 !!
99 boards left in the game
We rolled .... 62 !!
99 boards left in the game
We rolled .... 12 !!
99 boards left in the game
We rolled .... 68 !!
99 boards left in the game
We rolled .... 88 !!
99 boards left in the game
We rolled .... 54 !!
99 boards left in the game
We rolled .... 32 !!
99 boards left in the game
We rolled .... 17 !!
99 boards left in the 

IndexError: list index out of range